//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Juno.Scheduler.Preconditions.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Juno.Scheduler.Preconditions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// This query is for Failure Rate Precondition Provider
        /// </summary>
        internal static string ExperimentFailureRate {
            get {
                return ResourceManager.GetString("ExperimentFailureRate", resourceCulture);
            }
        }

        /// <summary>
        /// This query is for Experiment OFR provider
        /// </summary>
        internal static string ExperimentOFR {
            get {
                return ResourceManager.GetString("ExperimentOFR", resourceCulture);
            }
        }
        
        /// <summary>
        /// This query is for In Progress providers
        /// </summary>
        internal static string InProgressExperiments {
            get {
                return ResourceManager.GetString("InProgressExperiments", resourceCulture);
            }
        }

        /// <summary>
        /// This query is for OFR providers
        /// </summary>
        internal static string JunoOfr {
            get {
                return ResourceManager.GetString("JunoOfr", resourceCulture);
            }
        }

        /// <summary>
        /// This query is for overall team InProgress experiment provider
        /// </summary>
        internal static string OverallTeamInProgressExperiments {
            get {
                return ResourceManager.GetString("OverallTeamInProgressExperiments", resourceCulture);
            }
        }

        /// <summary>
        /// This query is for successful experiments provider
        /// </summary>
        internal static string SuccessfulExperiments {
            get {
                return ResourceManager.GetString("SuccessfulExperiments", resourceCulture);
            }
        }
    }
}
