//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Juno.Extensions.Telemetry.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Juno.Extensions.Telemetry.Properties.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;$schema&quot;: &quot;https://junodev01execution.azurewebsites.net/v1.0/schema&quot;,
        ///    &quot;contentVersion&quot;: &quot;1.0.0&quot;,
        ///    &quot;name&quot;: &quot;Juno IPU2019.2 Patrol Scrubber&quot;,
        ///    &quot;description&quot;: &quot;Validate the effect of IPU2019.2 on the Azure Gen 5 nodes running Intel Broadwell processors, with patrol scrubber update on RS1.8.&quot;,
        ///    &quot;metadata&quot;: {
        ///        &quot;teamName&quot;: &quot;CRC AIR&quot;,
        ///        &quot;email&quot;: &quot;crcair@microsoft.com&quot;,
        ///        &quot;owners&quot;: &quot;crcair&quot;
        ///    },
        ///    &quot;parameters&quot;: {
        ///        &quot;subscription&quot;: &quot;18493588-5750-4037-ab5d- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BigCrazyExperiment {
            get {
                return ResourceManager.GetString("BigCrazyExperiment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;id&quot;: &quot;1d4906bc-001d-424d-bec9-306b52cdda29&quot;,
        ///    &quot;created&quot;: &quot;2020-04-14T23:10:48.6569726Z&quot;,
        ///    &quot;lastModified&quot;: &quot;2020-04-14T23:10:48.6569739Z&quot;,
        ///    &quot;status&quot;: &quot;Pending&quot;,
        ///    &quot;definition&quot;: {
        ///        &quot;$schema&quot;: &quot;https://junodev01execution.azurewebsites.net/v1.0/schema&quot;,
        ///        &quot;contentVersion&quot;: &quot;1.0.0&quot;,
        ///        &quot;name&quot;: &quot;Juno IPU2019.2 Patrol Scrubber&quot;,
        ///        &quot;description&quot;: &quot;Validate the effect of IPU2019.2 on the Azure Gen 5 nodes running Intel Broadwell processors, with patrol scrubber upda [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BigCrazyExperimentInstance {
            get {
                return ResourceManager.GetString("BigCrazyExperimentInstance", resourceCulture);
            }
        }
    }
}
