//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Juno.Execution.AgentRuntime.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Juno.Execution.AgentRuntime.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ipmiutil ver 2.94
        ///isel: version 2.94
        ///-- BMC version 3.17, IPMI version 2.0 
        ///SEL  Size = 226 records (Used=13, Free=213)
        ///RecId | Date/Time  | SEV | Src | Evt_Type | Sensor | Evt_detail 
        ///0001 | 07/04/19 01:23:38 | INF | BMC  | Event Log | SEL  | Log Cleared 
        ///0002 | 07/04/19 01:23:43 | INF | BMC  | Power Unit | System Power  | Power Off     
        ///0003 | 07/04/19 01:23:44 | MIN | BMC  | Power Unit | System Power  | AC Lost 
        ///0004 | 07/04/19 01:41:49 | INF | BMC  | Microcontroller |  | chg to Running 
        ///0005 | 07/04/19  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExampleSelLogOutput {
            get {
                return ResourceManager.GetString("ExampleSelLogOutput", resourceCulture);
            }
        }
    }
}
