.set-or-replace StagingDataDictionary <|
    datatable (classificationSystem:string, classification:string, term:string, preferredTerm:string, createdTime:datetime)
    [
    "Juno", "ExperimentName", "MCU2019.2 Perf/RelSys Patrol Scrubber", "Patrol Scrubber MCU2019.2", datetime(2020-06-11),
    "Juno", "ExperimentName", "MCU2019.2 Perf/CPU Patrol Scrubber", "Patrol Scrubber MCU2019.2", datetime(2020-06-11),
    "Juno", "ExperimentName", "MCU2019.2 Perf/IO Patrol Scrubber", "Patrol Scrubber MCU2019.2", datetime(2020-06-11)
    ];